apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: rocketchat

  sources:
    - repoURL: https://rocketchat.github.io/helm-charts
      chart: rocketchat
      targetRevision: v6.25.3
      helm:
        releaseName: rocketchat
        valuesObject:
          image:
            tag: 7.10.0 # Set the Rocket.Chat release

          mongodb:
            image:
              repository: bitnamilegacy/mongodb
            volumePermissions:
              image:
                repository: bitnamilegacy/os-shell
            metrics:
              image:
                repository: bitnamilegacy/mongodb-exporter

            auth:
              passwords:
                - rocketchat
              rootPassword: rocketchatroot

          host: rocketchat.satriashp.cloud  # Replace with your Rocket.Chat domain

          extraEnv:
            - name: INITIAL_USER
              value: "true"
            - name: ADMIN_USERNAME
              value: admin
            - name: ADMIN_EMAIL
              value: admin@satriashp.cloud
            - name: ADMIN_PASS
              value: admin
    - repoURL: https://github.com/satriashp/rocket.chat
      targetRevision: main
      path: argocd/apps/rocketchat/httproute

  destination:
    name: "in-cluster"
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
