apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: rocket.chat

servers: 1
agents: 2

kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"

image: rancher/k3s:v1.31.5-k3s1

# network: k3d
subnet: "172.28.0.0/16"

volumes:
  - volume: ${PWD}/data:/var/lib/rancher/k3s/storage
    nodeFilters:
      - all

# files:
#   - source: |
#       apiVersion: v1
#       kind: Namespace
#       metadata:
#         name: argocd
#     destination: /var/lib/rancher/k3s/server/manifests/argocd-namespace.yaml

ports:
  - port: 0.0.0.0:80:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:443:443
    nodeFilters:
      - loadbalancer

registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
    # proxy:
    #   remoteURL: https://registry-1.docker.io # mirror the DockerHub registry
    #   username: ""
    #   password: ""
    volumes:
      - ${PWD}/data/registry:/var/lib/registry # persist registry data locally

  config: | # define contents of the `registries.yaml` file (or reference a file); same as `--registry-config /path/to/config.yaml`
    mirrors:
      "docker.io":
        endpoint:
          - "http://registry.localhost:5000"
      "registry.k8s.io":
        endpoint:
          - "http://registry.localhost:5000"
      "quay.io":
        endpoint:
          - "http://registry.localhost:5000"
      "public.ecr.aws":
        endpoint:
          - "http://registry.localhost:5000"
      "rancher":
        endpoint:
          - "http://registry.localhost:5000"
      "registry.rocket.chat":
        endpoint:
          - "http://registry.localhost:5000"

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*