apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: rocketchat

  sources:
    - path: .
      repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      targetRevision: 77.13.0
      helm:
        releaseName: monitoring
        valuesObject:
          crds:
            enabled: true
            upgradeJob:
              enabled: true
              forceConflicts: true

          grafana:
            defaultDashboardsTimezone: Asia/Jakarta
            sidecar:
              dashboards:
                enabled: true

          prometheus:
            prometheusSpec:
              podMonitorSelector:
                serviceMonitorSelectorNilUsesHelmValues: false
                podMonitorSelectorNilUsesHelmValues: false

    - repoURL: https://github.com/satriashp/rocket.chat
      targetRevision: main
      path: argocd/apps/monitoring/httproute

    - repoURL: https://github.com/satriashp/rocket.chat
      targetRevision: main
      path: argocd/apps/monitoring/dashboard

  destination:
    name: "in-cluster"
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
