apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: rocketchat

  sources:
    - path: .
      repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      targetRevision: 77.13.0
      helm:
        releaseName: monitoring
        valuesObject:
          defaultRules:
            create: false
          alertmanager:
            enabled: false

          grafana:
            defaultDashboardsTimezone: Asia/Jakarta

            route:
              main:
                enabled: true
                parentRefs:
                  - name: traefik-gateway
                    kind: Gateway
                    group: gateway.networking.k8s.io
                    sectionName: websecure
                hostnames:
                  - grafana.satriashp.cloud
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - name: monitoring-grafana
                        port: 80

    - repoURL: https://github.com/satriashp/rocket.chat
      targetRevision: main
      path: argocd/apps/monitoring/httproute

  destination:
    name: "in-cluster"
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
