# This rule is not used by the project rocketchat-backup-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.satriashp.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rocketchat-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: rocketchatbackup-admin-role
rules:
- apiGroups:
  - apps.satriashp.cloud
  resources:
  - rocketchatbackups
  verbs:
  - '*'
- apiGroups:
  - apps.satriashp.cloud
  resources:
  - rocketchatbackups/status
  verbs:
  - get
