---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.satriashp.cloud
  resources:
  - rocketchatbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.satriashp.cloud
  resources:
  - rocketchatbackups/finalizers
  verbs:
  - update
- apiGroups:
  - apps.satriashp.cloud
  resources:
  - rocketchatbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
