apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-backup-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # adjust size as needed
