apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: rocketchat

  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v37.1.1
    helm:
      releaseName: traefik
      valuesObject:
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`dashboard.satriashp.cloud`)
            entryPoints:
              - web

        providers:
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true

        ports:
          websecure:
            port: 443

        gateway:
          listeners:
            web:
              namespacePolicy:
                from: All
            websecure:
              protocol: HTTPS
              port: 443
              namespacePolicy:
                from: All
              certificateRefs:
                - name: satriashp-cloud-tls
                  kind: Secret
                  group: ""

        logs:
          access:
            enabled: true

  destination:
    name: "in-cluster"
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
