apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v37.1.1
    helm:
      releaseName: traefik
      valueFiles:
        - values.yaml

  destination:
    name: "in-cluster"
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
