apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: rocketchat
  source:
    path: argocd/apps/certificates
    repoURL: https://github.com/satriashp/rocket.chat
    targetRevision: main

  destination:
    name: "in-cluster"
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
