---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-cert
  namespace: default
spec:
  secretName: domain-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "chat.satriashp.cloud"
