apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    # Production endpoint
    server: https://acme-v02.api.letsencrypt.org/directory
    email: satriashp.tech@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
    - dns01:
        cloudflare:
          email: satriashp.tech@gmail.com   # Cloudflare account email
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
