apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-script
data:
  mongodump.sh: |
    #!/bin/bash

    TIMESTAMP=$(date -u +"%Y%m%dT%H%MZ")
    OUT="/data/backup-rocketchat-$TIMESTAMP"

    mongodump --uri="$MONGO_URI" --gzip --archive="$OUT.archive.gz" --verbose

  mongorestore.sh: |
    #!/bin/bash
    LATEST=$(ls -t /data/backup-rocketchat-*.archive.gz | head -n 1)
    mongorestore --uri="$MONGO_URI" --gzip --archive="$LATEST" --drop --verbose
